#!/usr/bin/env python3
"""Row COLDRTT's studies: the writer's golden g10 and g12 sources as AV1 payloads and as HTJ2K, 12 frames each.

Each source is regenerated by make_golden.py's own `content` and must hash to the golden payload's
.sha256 before it is coded, so one checksum judges both codecs' decodes.

usage: coldrtt_frames.py OJPH_COMPRESS OUT   — lab/page-open/README.md §Cold round trips by codec
"""
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "ingest/coded-frames"))
from make_golden import PAYLOADS, SETS, content  # noqa: E402

FRAMES = 12


def main():
    ojph, out = sys.argv[1], Path(sys.argv[2])
    for name in ("g10", "g12"):
        seed = list(SETS).index(name)
        ch, lo, hi, _ = SETS[name]
        px = content(ch, lo, hi, seed).astype("<u2")
        want = (PAYLOADS / "plain" / f"{name}.sha256").read_text().strip()
        if hashlib.sha256(px.tobytes()).hexdigest() != want:
            sys.exit(f"{name}: the regenerated source is not the golden payload's")
        h, w = px.shape[:2]
        bits = int(hi).bit_length()
        pgm = out / f"{name}.pgm"
        out.mkdir(parents=True, exist_ok=True)
        pgm.write_bytes(f"P5\n{w} {h}\n{(1 << bits) - 1}\n".encode() + px.astype(">u2").tobytes())
        # The served profile: lab/scripts/gen_htj2k_fixtures.sh's encode().
        j2c = out / f"{name}.j2c"
        subprocess.run([ojph, "-i", pgm, "-o", j2c, "-num_decomps", "5", "-block_size", "{64,64}",
                        "-prog_order", "RPCL", "-reversible", "true"], check=True, capture_output=True)
        for codec, ext, src in (("htj2k", "htj2k", j2c), ("av1", "av1", PAYLOADS / "plain" / f"{name}.av1")):
            d = out / f"{name}-{codec}"
            (d / "frames").mkdir(parents=True, exist_ok=True)
            for i in range(FRAMES):
                (d / "frames" / f"{i:03d}.{ext}").write_bytes(src.read_bytes())
            meta = {"frameCount": FRAMES, **({"codec": "av1"} if codec == "av1" else {})}
            (d / "metadata.json").write_text(json.dumps(meta) + "\n")
        (out / f"{name}.sha256").write_text(want + "\n")


if __name__ == "__main__":
    main()
