#!/usr/bin/env python3
"""An SBND study with realistic *geometry* and synthetic bytes, at an arbitrary size.

The read path does not care what the bytes are — the kernel copies 16 KB of wavelet
coefficients and 16 KB of zeros at the same cost. It cares about **where reads land, how far
apart, and how much data there is relative to RAM**. So a fixture built from a realistic
frame-size distribution buys nearly all the validity of real DICOM at none of the cost, and
that is what this writes.

The two properties the existing fixtures do not have:

* **Variable frame sizes.** `gen_live_cell_fixture.sh` writes uniform frames, which puts
  every frame boundary on a regular grid and makes a frame-major layout look more orderly
  than a real study is. Sizes here are lognormal about a mean, which shifts every later
  frame's start.
* **Larger than the page cache.** Every cell in the campaign so far force-evicts with
  `fadvise(DONTNEED)` and then reads a study that would comfortably fit in RAM, so a miss is
  always a *first* touch. A study larger than the cache misses because pages were
  **evicted under pressure**, which is a different regime and the one our deployment runs in.

Writes sparsely-filled data (a repeating pattern) via large buffered writes, so a 4 GB
fixture costs disk but little time.

    gen_geometry_fixture.py --out lab/fixtures/geom_4g --total-bytes 4e9 \\
        --frame-bytes 250000 --size-cv 0.6
"""
from __future__ import annotations

import argparse
import json
import math
import os
import random
import struct
from pathlib import Path

CHUNK = 8 << 20


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, required=True, help="fixture directory")
    ap.add_argument("--name", default=None, help="defaults to the directory name")
    ap.add_argument("--total-bytes", type=float, required=True)
    ap.add_argument("--frame-bytes", type=int, default=250_000, help="mean frame payload")
    ap.add_argument("--size-cv", type=float, default=0.6,
                    help="coefficient of variation of frame size; 0 for uniform")
    ap.add_argument("--seed", type=int, default=7)
    a = ap.parse_args()

    name = a.name or a.out.name
    total = int(a.total_bytes)
    rng = random.Random(a.seed)

    # Draw sizes until the target total is reached, so --total-bytes is honoured exactly
    # rather than approximated by a frame count.
    sizes: list[int] = []
    acc = 0
    if a.size_cv > 0:
        sigma = math.sqrt(math.log(1.0 + a.size_cv**2))
        mu = math.log(a.frame_bytes) - 0.5 * sigma * sigma
        draw = lambda: max(4096, int(rng.lognormvariate(mu, sigma)))  # noqa: E731
    else:
        draw = lambda: a.frame_bytes  # noqa: E731
    while acc < total:
        s = min(draw(), total - acc)
        if s < 4096:
            break
        sizes.append(s)
        acc += s
    n = len(sizes)

    meta = {
        "frameCount": n,
        "seriesLabel": name,
        "meanFrameBytes": a.frame_bytes,
        "sizeCv": a.size_cv,
        "note": "synthetic bytes, realistic geometry — see gen_geometry_fixture.py",
    }
    meta_bytes = json.dumps(meta, separators=(",", ":")).encode()
    data_base = 16 + 12 * n + len(meta_bytes)

    a.out.mkdir(parents=True, exist_ok=True)
    path = a.out / f"{name}.sbnd"
    with open(path, "wb") as f:
        f.write(b"SBND")
        f.write(struct.pack("<I", 1))
        f.write(struct.pack("<I", len(meta_bytes)))
        f.write(struct.pack("<I", n))
        off = data_base
        for s in sizes:
            f.write(struct.pack("<QI", off, s))
            off += s
        f.write(meta_bytes)
        # Real bytes, not a hole: a sparse file would let reads of unwritten ranges complete
        # without touching the device or the page cache, which would silently turn every
        # cold cell warm. Write a repeating pattern in large chunks.
        blob = bytes(range(256)) * (CHUNK // 256)
        remaining = acc
        while remaining > 0:
            k = min(CHUNK, remaining)
            f.write(blob[:k])
            remaining -= k

    (a.out / "metadata.json").write_text(json.dumps(meta, indent=2) + "\n")
    (a.out / "README.md").write_text(
        f"# {name}\n\n"
        f"{n} frames, mean {a.frame_bytes} B, size CV {a.size_cv}, "
        f"{os.path.getsize(path):,} bytes total.\n\n"
        "Synthetic bytes, realistic geometry. Generated by "
        "`lab/scripts/gen_geometry_fixture.py`; not committed.\n"
    )
    st = os.stat(path)
    print(f"wrote {path}: {st.st_size:,} bytes, {n} frames, "
          f"allocated {st.st_blocks * 512:,} (sparse if much lower)")


if __name__ == "__main__":
    main()
