#!/usr/bin/env python3
"""L2 ask-policy simulator — the shared ordered stream as a FIFO pipe with RTT.

Extends `l2_v2_order_model.py` (which reproduces the v2 rig rows with two parameters and no depth
term) into a model that can ask the question the campaigns could not: with a window that does not
wrap, traces that strand in-flight work, a reader that is faster or slower than the link, and depth
and prefetch varied independently, what does bounding the ask depth buy, and what does it cost?

Model (all times ms):
  * reader: step i wants frame f_i at t_i = i * step_ms and never waits for the network (open loop,
    like the harness: lateness is measured against the schedule, the schedule does not slip).
  * client: at every step and at every arrival it offers candidates in priority order — the centre
    frame first, then `prefetch` frames ahead in the direction of travel, clamped at the study edges
    — and issues each one that is neither cached nor in flight. The centre is always issued (a
    viewer asks for what is on screen); prefetch candidates are issued only while in_flight < D
    (D = None: unbounded). A prefetch candidate that does not fit is offered again at the next
    arrival or step; nothing is dropped.
  * path: an ask reaches the server after rtt/2 (+ c0, a per-ask fixed cost fitted on the rig rows);
    the server is serial and writes into a bottleneck that serialises at Tf = bytes / rate per frame,
    FIFO; the last byte reaches the client rtt/2 later, the first byte Tf earlier than that.
  * lateness_i = max(0, arrival(f_i) - t_i); wasted = bytes of frames that arrive but no step of the
    trace ever wants (the bytes a reversal or a jump strands).

Validation (`--validate`): fit (rate, c0) on the v2 CONTROL rows only, then predict the ring-D16
rows the campaign actually ran, with the v2 harness's wrapping window. The depth arms are never
fitted. Pass rule: within 2 % of the six-row mean; the effects this model ranks are 5-30 %.

Usage:
  python3 lab/scripts/l2_policy_sim.py --validate
  python3 lab/scripts/l2_policy_sim.py --grid [--step-ms 16|40]     # policies x traces x RTT
  python3 lab/scripts/l2_policy_sim.py --dynamic [--step-ms 16|40]  # estimator input: oracle vs contaminated
  python3 lab/scripts/l2_policy_sim.py --emit-traces lab/traces     # write the abandoned-work traces for the harness
"""
import argparse
import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
V2_TRACE = os.path.join(ROOT, "lab/traces/l2_ask_policy_scroll.json")

FRAME_BYTES = 32_004
U = 0.95
D_MIN, D_MAX = 1, 16


# ----------------------------------------------------------------------------- traces

def v2_trace(step_ms=16.0):
    steps = [s["frame"] for s in json.load(open(V2_TRACE))["steps"]]
    return {"name": "v2 scroll 0→79→40", "short": "l2_ask_policy_scroll", "steps": steps, "n": 80, "step_ms": step_ms}


def reversal_trace(n=80, turn=50, back_to=30, step_ms=16.0):
    """Scroll forward, turn, scroll back over frames already seen: prefetch past the turn is wasted
    bytes, and the frames behind the turn are cache hits."""
    steps = list(range(0, turn + 1)) + list(range(turn - 1, back_to - 1, -1))
    return {"name": f"reversal 0→{turn}→{back_to}", "short": "l2_reversal", "steps": steps, "n": n, "step_ms": step_ms}


def jump_trace(n=80, upto=25, jump_to=50, length=30, step_ms=16.0):
    """Scroll forward, then jump to an unseen region: everything prefetched past the jump sits in
    the FIFO ahead of the frames the reader now wants."""
    steps = list(range(0, upto + 1)) + list(range(jump_to, jump_to + length))
    return {"name": f"jump 0→{upto} then {jump_to}→{jump_to + length - 1}", "short": "l2_jump", "steps": steps, "n": n, "step_ms": step_ms}


def harness_json(trace):
    return {
        "name": trace["short"],
        "max_step": 1,
        "step_interval_ms": int(trace["step_ms"]),
        "settle_on": "last_asked",
        "send_cancel_on_settle": False,
        "_design": {"notes": f"{trace['name']}; {len(trace['steps'])} steps; study frameCount >= {trace['n']}. "
                              "Generated by lab/scripts/l2_policy_sim.py --emit-traces."},
        "steps": [{"frame": f} for f in trace["steps"]],
    }


# ----------------------------------------------------------------------------- windows

def forward_window(centre, direction, prefetch, n):
    """Centre, then `prefetch` frames ahead in the direction of travel, clamped at the study edges.
    Never wraps."""
    out = []
    f = centre
    while len(out) < 1 + prefetch and 0 <= f < n:
        out.append(f)
        f += direction
    return out


def ring_window(centre, direction, prefetch, n):
    """Port of the v2 harness's `window_frames(center, d, n)` with d = 1 + prefetch: centre ± radius
    modulo n. Kept only to reproduce the campaign; at the study start it asks for the last frames
    of the study, which is the artefact the adversarial review found."""
    d = 1 + prefetch
    out = [centre % n]
    r = 1
    while len(out) < d and r <= n:
        plus = (centre + r) % n
        if plus not in out:
            out.append(plus)
            if len(out) >= d:
                break
        minus = (centre + n - (r % n)) % n
        if minus not in out:
            out.append(minus)
        r += 1
    return out


class Policy:
    """depth: None = unbounded in-flight asks. prefetch: frames wanted ahead of the centre
    (None = the rest of the study). window_follows_depth: the v2 harness's coupling, where the
    prefetch count is D - 1 and moves with a dynamic D."""

    def __init__(self, depth=None, prefetch=0, shape=forward_window, name=None, window_follows_depth=False):
        self.depth, self.prefetch, self.shape = depth, prefetch, shape
        self.window_follows_depth = window_follows_depth
        self.name = name or f"{'unbounded' if depth is None else 'D=' + str(depth)}, {'no prefetch' if prefetch == 0 else 'prefetch ' + ('all' if prefetch is None else str(prefetch))}"


# ----------------------------------------------------------------------------- the pipe

class Sim:
    def __init__(self, trace, policy, rate_bps, rtt_ms, c0_ms=0.0, frame_bytes=FRAME_BYTES, dynamic=None):
        self.trace, self.policy = trace, policy
        self.tf = frame_bytes * 8 / rate_bps * 1000.0
        self.rtt, self.c0, self.frame_bytes = rtt_ms, c0_ms, frame_bytes
        self.dynamic = dynamic  # None or a DynamicDepth
        self.n = trace["n"]
        self.cache, self.in_flight = set(), {}  # frame -> (ask_t, in_flight_at_ask)
        self.pipe_free = 0.0
        self.events = []  # (arrival_t, frame, first_byte_t, ask_t, in_flight_at_ask)
        self.asks, self.wire_bytes, self.peak = 0, 0, 0
        self.arrival = {}
        self.direction = 1

    def depth(self):
        if self.dynamic is not None:
            return self.dynamic.current
        return math.inf if self.policy.depth is None else self.policy.depth

    def prefetch(self):
        if self.policy.window_follows_depth:
            return max(0, self.depth() - 1)
        return self.n if self.policy.prefetch is None else self.policy.prefetch

    def issue(self, frame, t):
        n_in = len(self.in_flight)
        self.in_flight[frame] = (t, n_in)
        self.asks += 1
        self.peak = max(self.peak, n_in + 1)
        start = max(t + self.rtt / 2 + self.c0, self.pipe_free)
        self.pipe_free = start + self.tf
        self.events.append((self.pipe_free + self.rtt / 2, frame, start + self.rtt / 2, t, n_in))
        self.events.sort()

    def pump(self, centre, t):
        for f in self.policy.shape(centre, self.direction, self.prefetch(), self.n):
            if f in self.cache or f in self.in_flight:
                continue
            if f != centre and len(self.in_flight) >= self.depth():
                break
            self.issue(f, t)

    def drain_until(self, t, centre):
        while self.events and self.events[0][0] <= t:
            arrival, frame, first_byte, ask_t, n_in = self.events.pop(0)
            self.in_flight.pop(frame, None)
            self.cache.add(frame)
            self.arrival[frame] = arrival
            self.wire_bytes += self.frame_bytes
            if self.dynamic is not None:
                self.dynamic.on_completed(first_byte - ask_t, self.frame_bytes, n_in, arrival, self.rtt)
            self.pump(centre, arrival)

    def run(self):
        steps, step_ms = self.trace["steps"], self.trace["step_ms"]
        centre = steps[0]
        for i, f in enumerate(steps):
            t = i * step_ms
            if i > 0 and f != steps[i - 1]:
                self.direction = 1 if f > steps[i - 1] else -1
            centre = f
            self.drain_until(t, centre)
            self.pump(centre, t)
        self.drain_until(math.inf, centre)
        lateness = []
        for i, f in enumerate(steps):
            if f not in self.arrival:
                raise RuntimeError(f"step {i}: frame {f} never arrived")
            lateness.append(max(0.0, self.arrival[f] - i * step_ms))
        wanted = set(steps)
        wasted = sum(self.frame_bytes for f in self.arrival if f not in wanted)
        return {
            "lateness": lateness, "wasted_bytes": wasted, "bytes_on_wire": self.wire_bytes,
            "asks": self.asks, "peak_in_flight": self.peak, "unique": len(self.arrival),
            "d_trajectory": self.dynamic.trajectory if self.dynamic else None,
        }


# ----------------------------------------------------------------------------- dynamic estimator

class DynamicDepth:
    """The lane's estimator: every 8 completions, RTT = median over the last 8 samples, Tf = median
    bytes / observed throughput, D = ceil(U (1 + RTT/Tf)), adopt after two equal evaluations,
    clamp [1, 16]. `rtt_source` picks what feeds RTT: 'oracle' (the true path RTT — what a transport
    RTT estimate would give), 'first_byte' (ask→first-byte, the v1/v2 input, which includes the
    client's own queue), 'clean' (ask→first-byte only from asks issued into an empty pipe; falls
    back to all samples when there are none, as the v2 harness does)."""

    def __init__(self, warm, rtt_source="first_byte"):
        self.current, self.rtt_source = warm, rtt_source
        self.samples, self.completed, self.last_computed = [], 0, None
        self.trajectory, self.computed = [], []

    def on_completed(self, first_byte_ms, nbytes, in_flight_at_ask, arrival, rtt_true):
        self.samples.append((first_byte_ms, nbytes, in_flight_at_ask, arrival))
        self.samples = self.samples[-8:]
        self.completed += 1
        self.trajectory.append(self.current)
        if self.completed >= 8 and self.completed % 8 == 0 and len(self.samples) == 8:
            if self.rtt_source == "oracle":
                rtt = rtt_true
            elif self.rtt_source == "clean":
                clean = [s[0] for s in self.samples if s[2] == 0]
                rtt = median(clean) if clean else median([s[0] for s in self.samples])
            else:
                rtt = median([s[0] for s in self.samples])
            span = self.samples[-1][3] - self.samples[0][3]
            if span > 0:
                thr = sum(s[1] for s in self.samples) * 8 * (7 / 8) / (span / 1000.0)
                tf = median([s[1] for s in self.samples]) * 8 / thr * 1000.0
                d = max(D_MIN, min(D_MAX, math.ceil(U * (1 + rtt / tf))))
                self.computed.append(d)
                if self.last_computed == d and d != self.current:
                    self.current = d
                self.last_computed = d


def median(xs):
    s = sorted(xs)
    n = len(s)
    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2


def mean(xs):
    return sum(xs) / len(xs)


# ----------------------------------------------------------------------------- reporting

def nearest_rank(sorted_asc, p):
    return sorted_asc[max(0, math.ceil(p / 100 * len(sorted_asc)) - 1)]


def dist(lat):
    s = sorted(lat)
    return {"median": nearest_rank(s, 50), "p75": nearest_rank(s, 75), "p95": nearest_rank(s, 95), "max": s[-1],
            "mean": mean(s), "late": sum(1 for x in s if x > 0) / len(s)}


def fmt(r):
    d = dist(r["lateness"])
    return (f"med={d['median']:7.1f} p95={d['p95']:7.1f} max={d['max']:7.1f} late={d['late']:.2f} "
            f"wasted_KB={r['wasted_bytes'] / 1000:5.0f} asks={r['asks']:4d} peak={r['peak_in_flight']:3d}")


def formula_depth(rtt_ms, tf_ms):
    return max(D_MIN, min(D_MAX, math.ceil(U * (1 + rtt_ms / tf_ms))))


# ----------------------------------------------------------------------------- modes

# loss = 0 rows of `docs/measurements/r2/l2_ask_policy_v2.tsv` on `cursor/l2-harness-fix-plan-c999`
# (p95_lateness_ms, runs 1..3). fixed16 and dynamic16 are the same policy: both ran D = 16 for the
# whole run (`d_min_observed = d_max_observed = 16` on every row), so six rows predict one number.
V2_ROWS = {
    20: {"control": [1521.9, 1521.2, 1518.4], "fixed16": [1617.0, 1610.3, 1627.4], "dynamic16": [1615.6, 1614.1, 1612.4]},
    60: {"control": [1632.1, 1671.9, 1641.5], "fixed16": [1744.6, 1742.0, 1745.9], "dynamic16": [1739.4, 1744.6, 1746.0]},
    150: {"control": [1903.3, 1909.1, 1956.1], "fixed16": [2010.5, 2014.5, 2005.8], "dynamic16": [2245.9, 1999.6, 2012.6]},
}
PASS_PCT = 2.0


def validate():
    tr = v2_trace()
    worst = 0.0
    for rtt, rows in V2_ROWS.items():
        ctrl_obs = mean(rows["control"])
        d16 = rows["fixed16"] + rows["dynamic16"]
        d16_obs, d16_spread = mean(d16), (max(d16) - min(d16)) / mean(d16) * 100
        best = None
        for mbps in [x / 100 for x in range(850, 1000, 2)]:
            for c0 in range(0, 1400, 5):
                r = Sim(tr, Policy(None, 0), mbps * 1e6, rtt, c0).run()
                err = (dist(r["lateness"])["p95"] - ctrl_obs) ** 2
                if best is None or err < best[0]:
                    best = (err, mbps, c0)
        _, mbps, c0 = best
        ctrl = Sim(tr, Policy(None, 0), mbps * 1e6, rtt, c0).run()
        ring = Sim(tr, Policy(16, 15, ring_window), mbps * 1e6, rtt, c0).run()
        fwd = Sim(tr, Policy(16, 15, forward_window), mbps * 1e6, rtt, c0).run()
        p_ring = dist(ring["lateness"])["p95"]
        err = abs(p_ring - d16_obs) / d16_obs * 100
        worst = max(worst, err)
        print(f"rtt{rtt:<4} fit on control mean {ctrl_obs:.1f}: rate={mbps:.2f} Mbps c0={c0} ms (model {dist(ctrl['lateness'])['p95']:.1f}, peak in flight {ctrl['peak_in_flight']})"
              f"\n        ring-D16 predicted {p_ring:.1f} vs six-row mean {d16_obs:.1f} [{min(d16):.1f}..{max(d16):.1f}]"
              f" -> error {err:.2f} %, rows' own spread {d16_spread:.2f} %"
              f"\n        the same D16 with a non-wrapping window would be {dist(fwd['lateness'])['p95']:.1f} (control {dist(ctrl['lateness'])['p95']:.1f})")
    ok = worst <= PASS_PCT
    print(f"worst prediction error: {worst:.2f} % (pass rule {PASS_PCT:.0f} %) -> "
          f"{'model reproduces the v2 grid' if ok else 'MODEL DOES NOT REPRODUCE THE GRID'}")
    return 0 if ok else 1


def arms(d):
    """The policies worth telling apart. d = the ADR's formula depth for the cell."""
    return [
        Policy(None, 0, name="unbounded, no prefetch (v2 control)"),
        Policy(None, d - 1, name=f"unbounded, prefetch {d - 1}"),
        Policy(d, 0, name=f"D={d}, no prefetch"),
        Policy(d, d - 1, name=f"D={d}, prefetch {d - 1}  (ADR window)"),
        Policy(16, 15, name="D=16, prefetch 15  (v2 fixed/dynamic)"),
        Policy(None, None, name="unbounded, prefetch all  (bulk ask)"),
        Policy(d, None, name=f"D={d}, prefetch all  (bounded commitment)"),
    ]


def grid(step_ms, rate_mbps=10.0, frame_bytes=FRAME_BYTES, rtts=(20, 60, 150)):
    tf = frame_bytes * 8 / (rate_mbps * 1e6) * 1000
    print(f"### step {step_ms} ms, Tf {tf:.1f} ms at {rate_mbps} Mbps: demand/supply {tf / step_ms:.2f} "
          f"({'reader faster than the link' if tf > step_ms else 'link faster than the reader'})")
    for tr in (v2_trace(step_ms), reversal_trace(step_ms=step_ms), jump_trace(step_ms=step_ms)):
        print(f"\n=== {tr['name']}  ({len(tr['steps'])} steps, {tr['n']} frames)")
        for rtt in rtts:
            d = formula_depth(rtt, tf)
            print(f"-- rtt {rtt} ms, formula D = {d}")
            for p in arms(d):
                r = Sim(tr, p, rate_mbps * 1e6, rtt, 0.0, frame_bytes).run()
                print(f"   {p.name:44} {fmt(r)}")


def dynamic(step_ms, rate_mbps=10.0, frame_bytes=FRAME_BYTES, rtts=(20, 60, 150)):
    tf = frame_bytes * 8 / (rate_mbps * 1e6) * 1000
    print(f"### dynamic estimator, step {step_ms} ms, Tf {tf:.1f} ms (demand/supply {tf / step_ms:.2f}); warm-up D = formula")
    for tr in (reversal_trace(step_ms=step_ms), jump_trace(step_ms=step_ms)):
        print(f"\n=== {tr['name']}")
        for rtt in rtts:
            d = formula_depth(rtt, tf)
            fixed = Sim(tr, Policy(d, d - 1), rate_mbps * 1e6, rtt, 0.0, frame_bytes).run()
            print(f"-- rtt {rtt:3} formula D {d:2}   fixed D, prefetch D-1              {fmt(fixed)}")
            for coupled in (True, False):
                for src in ("oracle", "first_byte", "clean"):
                    dyn = DynamicDepth(d, src)
                    pol = Policy(d, d - 1, window_follows_depth=coupled)
                    r = Sim(tr, pol, rate_mbps * 1e6, rtt, 0.0, frame_bytes, dynamic=dyn).run()
                    traj = r["d_trajectory"]
                    print(f"   rtt-source {src:10} {'window = D (v2)' if coupled else 'window = formula'}  "
                          f"D {min(traj):2}..{max(traj):2}  computed {dyn.computed[:6]}  {fmt(r)}")


def cell(a):
    """One policy on one cell, for cross-checking a harness run."""
    tr = {"v2": v2_trace, "reversal": reversal_trace, "jump": jump_trace}[a.trace](step_ms=a.step_ms)
    shape = ring_window if a.shape == "ring" else forward_window
    prefetch = None if a.prefetch < 0 else a.prefetch
    depth = None if a.depth == 0 else a.depth
    r = Sim(tr, Policy(depth, prefetch, shape), a.rate_mbps * 1e6, a.rtt, a.c0).run()
    print(f"sim {a.trace:8} step {a.step_ms:g} rtt {a.rtt:g} D={a.depth} prefetch={a.prefetch} {a.shape:7} {fmt(r)}")


def emit_traces(out_dir):
    for tr in (reversal_trace(), jump_trace()):
        path = os.path.join(out_dir, tr["short"] + ".json")
        with open(path, "w") as f:
            json.dump(harness_json(tr), f, indent=1)
        print(f"wrote {path} ({len(tr['steps'])} steps)")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--validate", action="store_true")
    ap.add_argument("--grid", action="store_true")
    ap.add_argument("--dynamic", action="store_true")
    ap.add_argument("--emit-traces", metavar="DIR")
    ap.add_argument("--step-ms", type=float, default=16.0)
    ap.add_argument("--rate-mbps", type=float, default=10.0)
    ap.add_argument("--cell", action="store_true", help="one policy on one cell (see --trace/--rtt/--depth/--prefetch/--shape)")
    ap.add_argument("--trace", choices=("v2", "reversal", "jump"), default="v2")
    ap.add_argument("--rtt", type=float, default=0.0)
    ap.add_argument("--c0", type=float, default=0.0, help="per-ask fixed cost (ms); 0 on loopback")
    ap.add_argument("--depth", type=int, default=0, help="0 = unbounded")
    ap.add_argument("--prefetch", type=int, default=0, help="-1 = the rest of the study")
    ap.add_argument("--shape", choices=("forward", "ring"), default="forward")
    a = ap.parse_args()
    rc = 0
    if a.cell:
        cell(a)
    if a.validate:
        rc = validate()
    if a.grid:
        grid(a.step_ms, a.rate_mbps)
    if a.dynamic:
        dynamic(a.step_ms, a.rate_mbps)
    if a.emit_traces:
        emit_traces(a.emit_traces)
    if not (a.validate or a.grid or a.dynamic or a.emit_traces or a.cell):
        ap.print_help()
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
